branches:
  only:
    - dev
    - master
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - yarn migrate:latest
  - yarn seed:run
script:
  - yarn lint
  - yarn flow
  - yarn test:coverage
