branches:
  only:
    - dev
    - master
language: node_js
node_js:
  - '8'
install:
  - yarn global add codecov
  - yarn
before_script:
  - yarn migrate:latest
  - yarn seed:run
script:
  - yarn lint
  - yarn test:coverage
  - codecov
