// flow-typed signature: b39d87d677fdb033911e9298ceee3235
// flow-typed version: <<STUB>>/kcors_v^2.2.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kcors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kcors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'kcors/index' {
  declare module.exports: $Exports<'kcors'>;
}
declare module 'kcors/index.js' {
  declare module.exports: $Exports<'kcors'>;
}
