// flow-typed signature: f7f8a2739c1a4b7a6b501eec9ecac8bf
// flow-typed version: <<STUB>>/koa-convert_v^1.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-convert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-convert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-convert/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-convert/index' {
  declare module.exports: $Exports<'koa-convert'>;
}
declare module 'koa-convert/index.js' {
  declare module.exports: $Exports<'koa-convert'>;
}
declare module 'koa-convert/test.js' {
  declare module.exports: $Exports<'koa-convert/test'>;
}
